document.write("<p>Versión: ");
document.write(navegador.version);
document.write("</p>");
document.write("<p>Plataforma: ");
document.write(navegador.idioma);
document.write("</p>");
document.write("<p>Vendedor: ");
document.write(navegador.vendedor);
document.write("</p>");
document.write("<p>Agente: ");
document.write(navegador.agente);
document.write("</p>");
document.write("<p>Java Activo: ");
document.write(navegador.javaActivo);
document.write("</p>");